### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [coltoutram/Colts-Cogs#9]
AutoRole, bancheck, speedtest and sysinfo no longer work on the updated version of Red.
Giving the error: 
RuntimeError: The BanList cog in the bancheck.bancheck package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement.

And so on

**Comment by coltoutram** [comment]
Yes I know theres an update with breaking changes I'll look into it when I have the time.

**Comment by coltoutram** [comment]
For now I've made a branch for the rc1 release, I will update the main branch later.
https://github.com/coltoutram/Colts-Cogs/tree/rc1
